gocd/ruby-functional-tests

lib/context/materials.rb, lib/context/scenario_state.rb
Pass along both environment name and the unique environment name for setting up a config repo environment
Issue caused due to looking for environment using unique_name instead of name into the scenario_state
=> Fix spec failure

Gemfile
Need 0.3.1 version of gauge ruby to be run on gauge version 0.7.0
=> Use specific version of gauge-ruby

Rakefile, lib/context/basic_configuration.rb, lib/pages/new_pipeline_dashboard_page.rb, specs/PipelineDashboardAutoRefresh.spec, step_implementations/initialize.rb, step_implementations/specs/configuration_spec.rb
* It disables new dashboard toggles after test run for AutoRefreshSpec
* It optimizes clean up after test runs
* It removes flakiness in AutoRefresh specs
=> New dashboard/disable toggle in teardown

lib/helpers/spec_helper.rb, lib/pages/data_sharing_spa.rb, specs/DataSharing.spec, step_implementations/specs/data_sharing_spa_spec.rb
* Verify admin users can toggle the information
* Verify save and reset permission operations
* Verify the data being displayed is the same data that /data_sharing/usagedata API returns
=> Add data sharing SPA specs

lib/pages/app_base.rb
This is to avoid differences with logout view on old pages and new pages
=> Always load dashboard page and then logout

lib/pages/app_base.rb
Element#hover has been behaving flaky, couldn’t rely on it. However will create an issue and try to see that we can get back to using logout on UI in the test
=> Force navigate to logout page

lib/pages/plugins_spa.rb
So selecting plugin headers which has id value as expected
=> Capybara Element#ancestor method did not respect exact_text key

lib/pages/job_settings_page.rb, resources/config/external-artifacts-cruise-config.xml, specs/ExternalArtifacts.spec, step_implementations/specs/job_settings_spec.rb
Verify env var being set, secure env var being set and a replacement of an existing env var.
Also, add the ability to move a task up and down within a job.
=> Verify env vars after fetching an external artifact

specs/DrainModeSPA.spec, specs/EnableDisableUsers.spec, step_implementations/initialize.rb
Do not delete screen shots folder. export it as artifact in jobs that are needed. Currently gauge html plugin is not showing up screenshot in the report
=> Fix User summary page message

.gitignore
Even if gauge fails to show up the screenshots on html report, this folder will have the screenshot grabbed during test failure
=> Add folder screenshots

lib/pages/admin_pipeline_page.rb
This is related to https://github.com/gocd/gocd/issues/5688. 
The dropdown for moving pipelines is actually present, but the id was changed (as part of the pipeline export work) so the css selector used in the test is no longer accurate. We chose to change the id because the same div is used for both the pipeline export dropdown list and the move to dropdown list. We wanted to make the id more general. 
This should fix the test broken as a result of the change.
=> Fixed text broken by pipeline export

lib/context/basic_configuration.rb, specs/AdminPermissionsNewUsers.spec, specs/AssociateUsersWithRoles.spec, specs/DisabledUserAccess.spec, specs/EnableDisableUsers.spec, specs/SystemAdminPrivilegeToggling.spec, specs/UserAPI.spec, step_implementations/specs/common_spec.rb
Specs will for now run with the user summary page on rails. Once we complete manual verification of the new user summary page, will modify spec to run on new page. Also need to add more steps  to validate new features like filters, search
=> Enable toggle  - users_page_using_rails - in specs

lib/pages/maintenance_mode_spa.rb
Not refreshing is leading to flaky test on build environment, so introducing this refresh
=> Refresh page before verifying for maintenance mode state

step_implementations/initialize.rb
Since its slowing down specs which needs to verify that certain actions does not exists
=> Reduce default_max_wait_time

specs/PipelineLayoutOperatePermissions.spec
So that it does not conflict with other spec which disable user of same name
=> Use different user

lib/pages/compare_pipeline_page.rb, resources/config/basic-secure-cruise-config.xml, specs/ManualRegisterationOfAgents.spec, specs/PluginsTabForm.spec, specs/SmokeTest.spec, specs/TemplatesAPI.spec, step_implementations/specs/configuration_spec.rb
Sometimes compare page has multiple materials and single commit, sometimes single material and multiple commits. Step implementation to take care of both scenarios
=> Modify step implementation to work for all spec data

specs/PipelinesUsingTimer.spec
In case of timer triggered pipeline with such short time as 30 secs, asserting for specific label of pipeline is not reliable, it causing intermittent test failure. Increasing the timer will slow down the test. The objective is to check if the pipeline is triggered by the timer or not. Which is validated by other steps. So removing this assertion of pipeline label
=> Removing the assertion for exact pipeline label

specs/SecretConfigAPI.spec
Fixes: SecretConfigAPI has wrong label for Capture state.
=> Fix teardown for SecretConfigAPI spec

Rakefile, step_implementations/specs/secret_config_api.rb
This is required for plugin side validation that takes place while creating or updating secret config. Without plugin creation will fail with plugin missing error.
=> Add file based secrets plugin for SecretConfigAPI spec

lib/pages/data_sharing_spa.rb, lib/pages/new_pipeline_dashboard_page.rb, lib/pages/personal_access_token_page.rb, lib/pages/plugins_spa.rb, lib/pages/server_backup_page.rb, lib/pages/server_health_messages.rb, lib/pages/user_summary.rb, specs/EditStagePermissionsWithPipelineGroupPermissions.spec
Previous versions of site prism was not validating the condition in load validation method which resulted in invalid validations being present and never identified. This commit fixes them
=> Fixes load validation failures

lib/pages/elastic_profiles_page.rb, specs/ElasticAgentProfilesCRUDOperations.spec, specs/ElasticProfiles.spec, step_implementations/specs/elastic_profiles_spec.rb
While expanding the cluster profile to perform crud operations on agent profile, the expand method clicks the cluster header panel. Sometimes the status report button is getting clicked which navigates to cluster status report page instead of expanding the panel. Fixed it by clicking on the plugin icon. Fixed some missing assertions
=> Fix for regression failure of elastic agents specs

lib/context/server.rb
-v will create the folder if it doesn’t exists, this gives false positive in case of EFS test as it will create the folder if mount is not present.
=> Use —mount instead of -v while mounting volumes on container

specs/PipelineApiSecurity.spec
Make sure the previous run passed before triggering another schedule
=> Added pipeline completed validation

lib/pages/new_pipeline_dashboard_page.rb
Regex should consider both seconds and minutes in the MTTR value
=> Fix analytics spec

Rakefile, lib/context/server.rb, resources/parameters.json, resources/template.json, step_implementations/go_constants.rb, step_implementations/initialize.rb
Added tests for running smoke on azure file system.
Setup:
1. We use an Azure EA to spin a VM on azure cloud.
2. Create a Premium Storage account in build-gocd resource group.
3. Create a file share in the storage account. File shares follow SMB protocol.
4. Mount the file share on a path "mnt/AzureFileShare" on the Azure VM using CIFS tools.
5. Service Prinicpal is used to authenticate the all create/delete/mount calls. Service Principal is stored in team 1Password as : Azure File System Service Principal
Test:
The test brings up a docker agent with two distinct mount points 
1. /mnt/AzureFileShare:/godata: This is to ensure we use Azure File share for storage.
2. /root/.gitconfig:/home/go/.gitconfig: This is to mitigate the jgit bug which by default does not set the …
=> Azure file system test

resources/config/auth-plugins-config.xml, resources/config/basic-cruise-config.xml, resources/config/basic-secure-cruise-config.xml, resources/config/basic-single-pipeline-config.xml, resources/config/conflict-cruise-config-for-pipelineAdmin.xml, resources/config/conflict-cruise-config.xml, resources/config/external-artifacts-cruise-config.xml, resources/config/fanin-cruise-config.xml, resources/config/group-admin-security-config.xml, resources/config/invalid-cruise-config.xml, resources/config/multiple-agents-cruise-config.xml, resources/config/permissions-cruise-config.xml, resources/config/secure-cruise-config.xml, resources/config/template-admin-cruise-config.xml, resources/config/tfs-cruise-config.xml, resources/config/with-config-repo-cruise-config.xml, resources/config/with-environments-cruise-config.xml
- Remove `artifactDir` from server attribute.
- Add `artifacts` as a config subtag in the server tag.
=> Fixes for config xml migration 132 -

lib/context/server.rb
Since this commit - https://github.com/gocd/gocd/commit/47ecfb070c91932c005445868e5f4f2f55296e99 - centos-7 image of GoCD server is not created
=> Update server image os to test as centos-8

README.md, lib/context/server.rb, resources/config/secure-cruise-config.xml, specs/EditStagePermissions.spec, specs/PipelineApiSecurity.spec
In https://github.com/gocd/gocd/pull/8034, the default permission for pipeline groups without any authorization defined is to deny, rather than allow everyone to be viewers and operators.
While reviewing, turn off whitespace changes: https://github.com/gocd/ruby-functional-tests/pull/651/files?diff=unified&w=1
Approach taken: Since the default permissions are changing, the configuration is changed to make it similar to the earlier setup.
Also: Changed one spec to verify https://github.com/gocd/gocd/pull/8034: This is done: [here](https://github.com/gocd/ruby-functional-tests/pull/651/files#diff-e11b04bb0bbb4d23bee82e3b56f75558R23), [here](https://github.com/gocd/ruby-functional-tests/pull/651/files#diff-e11b04bb0bbb4d23bee82e3b56f75558R86) and …
=> Allow defaulting group permissions to deny if no group auth setup

lib/pages/new_pipeline_dashboard_page.rb, resources/config/secure-cruise-config.xml, specs/PipelineDashboardManualTrigger.spec, step_implementations/specs/new_pipeline_dashboard_spec.rb
- verify no manual gate shows up for first manual stage from the pipeline.
- verify manual gate for manual stages.
- verify enabled/disabled state of manual gates.
- verify triggering of manual stage.
- verify users with view permissions do not have access to trigger manual gate.
=> Add specs to verify manual stage trigger on dashboard.

lib/pages/new_pipeline_dashboard_page.rb, specs/DashboardStageOverviewOlderRuns.spec, step_implementations/specs/dashboard_stage_overview_spec.rb
* Verify older runs dropdown shows up for stages which are run
more than 1s.
* Ability to navigate to an older stage run.
* Ability to navigate to an older stage run and rerun failed jobs.
=> Add specs for older stages runs on the dashboard stage overview.

lib/context/server.rb, specs/StartServerInMaintenanceMode.spec, step_implementations/go_constants.rb, step_implementations/specs/maintenance_mode_spa_spec.rb
* Specify the system property to start server in maintenance mode.
* Set the property value to false to verify GoCD Server does not
start in maintenance mode.
=> Add specs to start GoCD Server in maintenance mode.

Gemfile.lock
Reverts gocd/ruby-functional-tests#941
This broke something on Linux arm64.
=> Revert "Bump selenium-webdriver from 4.10.0 to 4.11.0"

Gemfile.lock
Reverts gocd/ruby-functional-tests#957
See https://github.com/SeleniumHQ/selenium/issues/12651
=> Revert "Bump selenium-webdriver from 4.10.0 to 4.12.0"
