gocd/ruby-functional-tests

step_implementations/go_constants.rb

Reverts gocd/ruby-functional-tests#48

Revert "Set stdout redirect file"

---

step_implementations/specs/agents_spa_spec.rb

to avoid inconsistent behavior in different environments

Assert if expected list as subset of agents displayed

---

Rakefile
specs/ArtifactStoreAPI.spec
step_implementations/specs/artifact_store_api_spec.rb
step_implementations/specs/login_spec.rb

The `DOCKER_REGISTRY_ARTIFACT_PLUGIN_RELEASE_URL` will need to be updated when a release is out. (Apparently the `/latest` path doesn't work with pre-releases)

Add tests for Artifact Store API

---

lib/context/materials.rb
lib/context/scenario_state.rb
lib/helpers/spec_helper.rb
lib/pages/stage_details_page.rb
resources/config/basic-cruise-config.xml
specs/BuildCause.spec
step_implementations/specs/new_pipeline_dashboard_spec.rb
step_implementations/specs/stage_details_spec.rb

* This is to test trigger behavior in the new dashboard. It ensures that pipelines when triggered pick up the correct revisions.

Build cause specs for the new dashboard

---

Rakefile
lib/helpers/spec_helper.rb
lib/pages/dashboard_personalization.rb
lib/pages/new_pipeline_dashboard_page.rb
resources/config/secure-cruise-config.xml
specs/PersonalizationView.spec
specs/PipelineSelector.spec
specs/PipelineSelectorWithSecurity.spec
step_implementations/specs/pipeline_selection_spec.rb

Very much so a WIP, but opening this so others can see my progress
EDIT: no longer a WIP

Personalization specs

---

lib/context/agents.rb
lib/context/server.rb
resources/with-java.sh
specs/FanInBehaviorForInconsistentRevisions.spec
step_implementations/go_constants.rb

Use java versions based on pipeline counter

---

resources/config/auth-plugins-config.xml
resources/config/basic-cruise-config.xml
resources/config/basic-secure-cruise-config.xml
resources/config/basic-single-pipeline-config.xml
resources/config/external-artifacts-cruise-config.xml
resources/config/fanin-cruise-config.xml
resources/config/multiple-agents-cruise-config.xml
resources/config/secure-cruise-config.xml
resources/config/with-config-repo-cruise-config.xml
resources/config/with-environments-cruise-config.xml

This shouldn't me merged until https://github.com/gocd/gocd/pull/5180 is merged

Bumping schema version to 114

---

lib/pages/agents_spa.rb

To be merged with [gocd PR 5245](https://github.com/gocd/gocd/pull/5245)

Update agents page selectors as per latest changes

---

lib/pages/app_base.rb

Remove the hardcoded sleep added

---

lib/pages/compare_pipeline_page.rb
specs/ComparePipelineTimelineView.spec
step_implementations/specs/compare_pipelines_spec.rb

Added spec ComparePipelineTimelineView

Compare pipeline timeline view

---

lib/context/basic_configuration.rb
lib/pages/new_pipeline_dashboard_page.rb
specs/AdminPermissionsNewUsers.spec
specs/AdminRolesAndNewUsers.spec
step_implementations/specs/configuration_spec.rb
step_implementations/specs/login_spec.rb

Added Spec AdminRolesAndUsers.

Admin roles and users

---

step_implementations/specs/data_sharing_spa_spec.rb
step_implementations/specs/new_pipeline_dashboard_spec.rb

Add some messages to the PipelineVisibility check since unable to reproduce the failure locally

Use v3 of usage data api

---

resources/config/permissions-cruise-config.xml
specs/PipelineDashboardAndActivitySecurityWithMultiplePermissions.spec
specs/PipelineDashboardAndPipelineActivitySecurity.spec
specs/PipelineDashboardAndPipelineActivitySecurityAtStageLevel.spec

This is to fix an ongoing regression failure

 reduced sleep time in job and added logout tear down step

---

lib/pages/job_settings_page.rb
specs/AdminTaskListing.spec
step_implementations/specs/job_settings_spec.rb

Removed some waits & duplicate methods

Removed some waits & duplicate methods

---

lib/helpers/spec_helper.rb
lib/pages/job_settings_page.rb
lib/pages/parameters_page.rb
lib/pages/publish_artifacts_view.rb
resources/config/basic-cruise-config.xml
specs/ArtifactsEditValidations.spec
specs/TaskViewerAndEditorEditFlow.spec
step_implementations/specs/job_settings_spec.rb

Added spec ArtifactsEditValidations & added element.set instead of element.native.clear job_settings_page.rb

Artifacts edit validations

---

lib/pages/user_summary.rb
specs/AssociateUsersWithRoles.spec
step_implementations/specs/user_summary_spec.rb

Adding spec AssociateUsersWithRoles

adding spec AssociateUsersWithRoles

---

lib/context/scenario_state.rb
lib/pages/job_details_page.rb
lib/pages/new_pipeline_dashboard_page.rb
resources/config/basic-cruise-config.xml
specs/RerunStage.spec
step_implementations/specs/job_details_spec.rb
step_implementations/specs/new_pipeline_dashboard_spec.rb

added spec RerunStage

---

lib/pages/plugins_spa.rb

To be Merged only after new plugins spa is default

Fix plugins specs to work with new compoentized plugins spa

---

lib/context/basic_configuration.rb
lib/pages/admin_pipeline_page.rb
resources/config/basic-cruise-config.xml
resources/config/invalid-cruise-config.xml
resources/config/secure-cruise-config.xml
specs/CruiseErrorMessages.spec
specs/GlobalMessages.spec
step_implementations/specs/admin_pipeline_page_spec.rb
step_implementations/specs/configuration_spec.rb
step_implementations/specs/materials_spec.rb
step_implementations/specs/new_pipeline_dashboard_spec.rb

Added spec GlobalMessages & CruiseErrorMessages

Global messages

---

lib/context/basic_configuration.rb
resources/config/basic-cruise-config.xml
resources/config/secure-cruise-config.xml
specs/AllowOnlyKnownUsersToLogin.spec
specs/ParamSubstitution.spec
step_implementations/specs/configuration_spec.rb

PR for AllowOnlyKnownUsersToLogin, ParamSubstitution

added two specs AllowOnlyKnownUsersToLogin, ParamSubstitution

---

lib/pages/stage_details_page.rb
resources/config/secure-cruise-config.xml
specs/PipelineLayoutOperatePermissions.spec
step_implementations/specs/configuration_spec.rb
step_implementations/specs/new_pipeline_dashboard_spec.rb
step_implementations/specs/stage_details_spec.rb

PR for new spec pipelineLayoutOperatePermissions

added spec pipelineLayoutOperatePermissions

---

lib/pages/stage_details_page.rb
resources/config/secure-cruise-config.xml
specs/PipelineLayoutStageActions.spec
step_implementations/specs/stage_details_spec.rb

PR for PipelineLayoutStageActions

Added spec PipelineLayoutStageActions.spec

---

lib/pages/authorization_config_spa.rb
specs/AuthConfigSPA.spec
step_implementations/specs/authorization_config_spec.rb

added specs for auth config spa

---

lib/context/basic_configuration.rb
lib/pages/artifacts_store_page.rb
lib/pages/authorization_config_spa.rb
lib/pages/job_details_page.rb
lib/pages/job_settings_page.rb
lib/pages/role_config_spa.rb
lib/pages/stage_details_page.rb
resources/config/basic-cruise-config.xml
specs/AuthConfigSPA.spec
specs/JobDetailsBreadCrumbs.spec
specs/JobRerun.spec
specs/JobRerunConfigDeletion.spec
specs/JobRerunRunMultipleInstance.spec
step_implementations/specs/authorization_config_spec.rb
step_implementations/specs/job_details_spec.rb
step_implementations/specs/job_settings_spec.rb
step_implementations/specs/pipeline_history_spec.rb
step_implementations/specs/stage_details_spec.rb

PR for JobRerun.spec,JobRerunConfigDeletion.spec

Added spec JobRerun.spec,JobRerunConfigDeletion.spec

---

lib/pages/job_details_page.rb
step_implementations/specs/job_details_spec.rb

Reverts gocd/ruby-functional-tests#265

Revert "test commit to verify the console output on buil.gocd , this commit w…"

---

specs/JobRerun.spec
specs/JobRerunRunMultipleInstance.spec
step_implementations/specs/job_details_spec.rb

PR for implementation for verifying environment variable on job console

corrected implementation for verifying environment variable on job console

---

lib/pages/job_details_page.rb
lib/pages/stage_details_page.rb
resources/config/basic-cruise-config.xml
specs/JobRerun.spec
specs/JobRerunRunMultipleInstance.spec
specs/StageDetails.spec
specs/StageDetailsJobTab.spec
specs/StageDetailsJobTabAutoRefresh.spec
step_implementations/specs/job_details_spec.rb
step_implementations/specs/new_pipeline_dashboard_spec.rb
step_implementations/specs/stage_details_spec.rb

PR for StageDetails.spec, StageDetailsJobTab,StageDetailsJobTabAutoRefresh

Stage details new

---

resources/config/basic-cruise-config.xml
specs/StageDetails.spec

PR for pipeline names changed for stagedetails spec to resolve git material is being used more than once in pipelines.

changed  pipeline names for stagedetails spec

---

lib/pages/job_details_page.rb
specs/JobRerun.spec
step_implementations/specs/job_details_spec.rb

PR for correction in jobRerun Spec

corrected implementation in JobRerun spec

---

lib/pages/job_settings_page.rb
lib/pages/pipeline_creation_wizard.rb
lib/pages/stage_settings_page.rb
resources/config/secure-cruise-config.xml
specs/EditJob.spec
specs/EditStage.spec
specs/EditStageAddNewJobFlow.spec
step_implementations/specs/job_settings_spec.rb
step_implementations/specs/pipeline_creation_wizard_spec.rb
step_implementations/specs/stage_details_spec.rb
step_implementations/specs/stage_settings_spec.rb

added spec EditJob

---

lib/context/basic_configuration.rb
lib/pages/stage_settings_page.rb
specs/EditStagePermissions.spec
step_implementations/specs/configuration_spec.rb
step_implementations/specs/stage_settings_spec.rb

PR for spec EditStagePermissions.spec

Added EditStagePermissions.spec

---

lib/pages/admin_pipeline_page.rb
specs/CreateAndDeletePipelineGroups.spec
step_implementations/specs/admin_pipeline_page_spec.rb

PR for CreateAndDeletePipelineGroups.spec

Added CreateAndDeletePipelineGroups

---

lib/pages/admin_pipeline_page.rb
specs/ClonePipeline.spec
step_implementations/specs/admin_pipeline_page_spec.rb

Added ClonePipeline

---

lib/pages/admin_pipeline_page.rb
lib/pages/pipeline_creation_wizard.rb
specs/EditPipelineGroups.spec
step_implementations/specs/admin_pipeline_page_spec.rb
step_implementations/specs/pipeline_creation_wizard_spec.rb

PR for EditPipelineGroups.spec

Added EditPipelineGroups.spec

---

lib/pages/admin_pipeline_page.rb
step_implementations/specs/admin_pipeline_page_spec.rb

After verifying for pipeline move is not allowed, close the dropdown

---

specs/PluginsTabForm.spec

Fix failing spec for https://github.com/gocd/gocd/pull/5713

Update auth plugin version in PluginsTabForm spec

---

lib/context/server.rb
specs/FanInBehaviorStageFailAndCancel.spec
specs/FanInBehaviorWithDifferentConfiguration.spec
specs/FanInOffBehavior.spec
specs/FanInOffBehaviorBlacklistingForTriangleConfiguration.spec
specs/FaninMultipleStagesDeepTriangle.spec
step_implementations/specs/common_spec.rb

PR for FaninMultipleStagesDeepTriangle,FanInOffBehaviorBlacklistingForTriangleConfiguration.spec,FaninMultipleStagesDeepTriangle.spec

PR for FaninMultipleStagesDeepTriangle,FanInOffBehaviorBlacklistingForTriangleConfiguration.spec,FaninMultipleStagesDeepTriangle.spec

---

resources/config/basic-cruise-config.xml
specs/PipelinesUsingTimer.spec

PR for Correcting PipelinesUsingTimer spec

Corrected PipelinesUsingTimer

---

lib/pages/environments_edit_page.rb

Haven't tested this locally because I'm not able to run the tests on my box. (Does the README need to be updated?)

Fix selector for agent checkbox

---

lib/pages/admin_pipeline_page.rb
lib/pages/new_pipeline_dashboard_page.rb
lib/pages/pipeline_settings_page.rb
lib/pages/stage_details_page.rb
resources/config/basic-cruise-config.xml
resources/config/group-admin-security-config.xml
resources/config/secure-cruise-config.xml
specs/PipelineGroupAdminsForSuperAdmin.spec
specs/PipelineGroupAdminsForUserWithNoPermission.spec
specs/PipelineGroupAdminsWithStageSecurity.spec
specs/PipelineGroupPermissionsForUserWithOperateViewAndAdmin.spec
specs/PipelineMaterialViewerAndEditor.spec
specs/StageDetailConfigChangedPopup.spec
specs/StageDetailsAutoRefresh.spec
specs/StageLocking.spec
step_implementations/specs/admin_pipeline_page_spec.rb
step_implementations/specs/new_pipeline_dashboard_spec.rb
step_implementations/specs/pipeline_api_spec.rb
step_implementations/specs/pipeline_settings_spec.rb
step_implementations/specs/stage_details_spec.rb

PR for PipelineGroupAdmin & StageDetails related specs

Adding PipelineGroupAdmin & StageDetails related specs

---

resources/config/basic-cruise-config.xml

PR for Reduced sleep time to correct StageLocking.spec

Reduced sleep time to correct StageLocking.spec

---

lib/pages/stage_details_page.rb
resources/config/basic-cruise-config.xml
resources/config/secure-cruise-config.xml
specs/StageSecurityForAutoApproval.spec
specs/StageWithCleanWorkingDIrAttribute.spec
step_implementations/specs/new_pipeline_dashboard_spec.rb
step_implementations/specs/stage_details_spec.rb

PR for Adding StageSecurityForAutoApproval.spec, StageWithCleanWorkingDIrAttribute.spec

Adding StageSecurityForAutoApproval.spec, StageWithCleanWorkingDIrAttribute.spec

---

lib/pages/job_settings_page.rb
lib/pages/stage_details_page.rb
lib/pages/stage_settings_page.rb
resources/config/basic-cruise-config.xml
resources/config/secure-cruise-config.xml
specs/EditStagePermissions.spec
specs/StageSecurityForAutoApproval.spec
specs/StageWithCleanWorkingDIrAttribute.spec
specs/TaskReordering.spec
specs/TaskViewerAndEditorValidations.spec
step_implementations/specs/job_settings_spec.rb
step_implementations/specs/new_pipeline_dashboard_spec.rb
step_implementations/specs/stage_details_spec.rb

PR for TaskReordering.spec,TaskViewerAndEditorValidations.spec

Adding TaskReordering.spec,TaskViewerAndEditorValidations.spec

---

lib/pages/compare_pipeline_page.rb
lib/pages/stage_details_page.rb
resources/config/basic-cruise-config.xml
resources/config/secure-cruise-config.xml
specs/ComparePipelinesWithDifferentPermissions.spec
specs/DependencyWalkInPipelineCompareWithSameScm.spec
specs/PipelineDependencyChaining.spec
step_implementations/specs/compare_pipelines_spec.rb
step_implementations/specs/new_pipeline_dashboard_spec.rb
step_implementations/specs/stage_details_spec.rb

PR for Adding spec DependencyWalkInPipelineCompareWithSameScm.spec, ComparePipelinesWithDifferentPermissions.spec, PipelineDependencyChaining.spec

Adding spec DependencyWalkInPipelineCompareWithSameScm.spec, ComparePipelinesWithDifferentPermissions.spec, PipelineDependencyChaining.spec

---

lib/pages/general_settings_page.rb
lib/pages/pipeline_creation_wizard.rb
lib/pages/pipeline_settings_page.rb
resources/config/basic-cruise-config.xml
specs/EditPipelineWizardCronFieldValidations.spec
specs/EditPipelineWizardPagesAndTabs.spec
specs/EditPipelineWizardReorderStages.spec
step_implementations/specs/general_settings_spec.rb
step_implementations/specs/job_settings_spec.rb
step_implementations/specs/pipeline_creation_wizard_spec.rb
step_implementations/specs/pipeline_settings_spec.rb

PR for Adding spec EditPipelineWizardCronFieldValidations, EditPipelineWizardPagesAndTabs, EditPipelineWizardReorderStages

Adding spec EditPipelineWizardCronFieldValidations, EditPipelineWizardPagesAndTabs, EditPipelineWizardReorderStages

---

specs/HungJobTermination.spec

PR for Adding wait time in HungJobTermination.spec

Added wait time in HungJobTermination.spec

---

lib/context/basic_configuration.rb
lib/pages/admin_pipeline_page.rb
lib/pages/pipeline_creation_wizard.rb
lib/pages/pipeline_settings_page.rb
resources/config/conflict-cruise-config-for-pipelineAdmin.xml
resources/config/conflict-cruise-config.xml
specs/ClickyAdminDirtyPageCheck.spec
specs/ConfigMergeGitConflict.spec
specs/ConfigMergeGitConflictForPipelineAdmin.spec
step_implementations/specs/admin_pipeline_page_spec.rb
step_implementations/specs/configuration_spec.rb
step_implementations/specs/pipeline_api_spec.rb
step_implementations/specs/pipeline_creation_wizard_spec.rb
step_implementations/specs/pipeline_settings_spec.rb

PR for spec ConfigMergeGitConflict and ConfigMergeGitConflictForPipelineAdmin.

Adding spec ConfigMergeGitConflict and ConfigMergeGitConflictForPipelineAdmin.

---

lib/pages/compare_pipeline_page.rb
lib/pages/pipeline_creation_wizard.rb
lib/pages/pipeline_settings_page.rb
resources/config/basic-cruise-config.xml
specs/MaterialCheckConnectivity.spec
specs/ModificationsBetweenPipelines.spec
step_implementations/specs/pipeline_creation_wizard_spec.rb
step_implementations/specs/pipeline_settings_spec.rb

PR fo spec MaterialCheckConnectivity & ModificationsBetweenPipelines

Adding spec MaterialCheckConnectivity & ModificationsBetweenPipelines

---

resources/config/basic-cruise-config.xml
resources/config/secure-cruise-config.xml
specs/PipelineDependencyTriangle.spec
specs/PipelineUnlocking-ErrorMessages.spec
specs/PipelineUnlocking.spec
step_implementations/specs/common_spec.rb
step_implementations/specs/pipeline_api_spec.rb

PR for Adding spec PipelineDependencyTriangle,PipelineUnlocking-ErrorMessages,PipelineUnlocking

Pipeline dependency triangle

---

lib/pages/admin_pipeline_page.rb
lib/pages/new_pipeline_dashboard_page.rb
lib/pages/pipeline_creation_wizard.rb
lib/pages/stage_details_page.rb
lib/pages/stage_settings_page.rb
specs/PauseNewPipelineAfterCreation.spec
specs/PermissionsForStageAndJobDetails.spec
specs/PipelineApprovalConfigurations.spec
step_implementations/specs/admin_pipeline_page_spec.rb
step_implementations/specs/new_pipeline_dashboard_spec.rb
step_implementations/specs/pipeline_creation_wizard_spec.rb
step_implementations/specs/stage_details_spec.rb
step_implementations/specs/stage_settings_spec.rb

PR for  PauseNewPipelineAfterCreation.spec,PermissionsForStageAndJobDetails.spec,PipelineApprovalConfigurations.spec

Adding spec PauseNewPipelineAfterCreation.spec,PermissionsForStageAndJobDetails.spec,PipelineApprovalConfigurations.spec

---

lib/pages/pipeline_group_edit_page.rb
resources/config/basic-cruise-config.xml
specs/AdministrationApiSecurity.spec
specs/BasicParamSubstitutionWithTemplate.spec
step_implementations/specs/pipeline_group_edit_spec.rb

PR for  specs AdministrationApiSecurity ,BasicParamSubstitutionWithTemplate

Adding specs AdministrationApiSecurity ,BasicParamSubstitutionWithTemplate

---

lib/pages/pipeline_creation_wizard.rb
specs/PauseNewPipelineAfterCreation.spec
specs/StageDetailConfigChangedPopup.spec

PR for putting wip tag for PauseNewPipelineAfterCreation.spec,StageDetailConfigChangedPopup.spec

putting wip tag for PauseNewPipelineAfterCreation.spec,StageDetailConfigChangedPopup.spec

---

lib/context/basic_configuration.rb
lib/context/materials.rb
lib/pages/job_details_page.rb
resources/config/basic-cruise-config.xml
specs/ArtifactMD5Verification.spec
specs/ArtifactMD5VerificationFailure.spec
specs/ArtifactMD5VerificationSkip.spec
step_implementations/specs/job_details_spec.rb
step_implementations/specs/new_pipeline_dashboard_spec.rb

PR for Artifact md5 verification related specs

Artifact md5 verification

---

lib/pages/job_settings_page.rb
resources/config/basic-cruise-config.xml
specs/AssociatingAPipelineWithAnEnvironmentWithNoAgents.spec
specs/AssociatingMultiplePipelinesWithAnEnvironment.spec
step_implementations/specs/agents_api.rb
step_implementations/specs/job_settings_spec.rb

PR for AssociatingAPipelineWithAnEnvironmentWithNoAgents.spec, AssociatingMultiplePipelinesWithAnEnvironment.spec

Adding spec AssociatingAPipelineWithAnEnvironmentWithNoAgents.spec, AssociatingMultiplePipelinesWithAnEnvironment.spec

---

Gemfile.lock
lib/context/basic_configuration.rb
lib/context/materials.rb
lib/context/scenario_state.rb
lib/pages/new_pipeline_dashboard_page.rb
resources/config/secure-cruise-config.xml
specs/AddNewPipelineGroupAdmin.spec
specs/PipelineApiSecurity.spec
specs/PipelineApis.spec
step_implementations/specs/configuration_spec.rb
step_implementations/specs/job_details_spec.rb
step_implementations/specs/pipeline_api_spec.rb

PR for specs  commiting specs PipelineApiSecurity.spec,PipelineApis.spec

Committing specs  commiting specs PipelineApiSecurity.spec,PipelineApis.spec

---

Gemfile.lock
lib/pages/job_details_page.rb
resources/config/secure-cruise-config.xml
specs/ArtifactAndPropertiesSecurity.spec
specs/ArtifactUploadFetch.spec
specs/concepts/verifyPropertyWithValueForPipelineStageLabelCounterJobCanBeAdded.cpt
specs/concepts/verifyPropertyWithValueForPipelineStageLabelCounterJobCannotBeAdded.cpt
step_implementations/specs/job_details_spec.rb

PR for specs ArtifactUploadFetch.spec, ArtifactAndPropertiesSecurity.spec

Artifact and properties security

---

lib/pages/config_xml_page.rb

Use contains rather than include - validate the expected set is a subset of actual

Fix regression failure

---

lib/pages/admin_pipeline_page.rb
lib/pages/general_settings_page.rb
lib/pages/job_settings_page.rb
resources/config/basic-cruise-config.xml
specs/AddNewTemplate.spec
step_implementations/specs/admin_pipeline_page_spec.rb
step_implementations/specs/general_settings_spec.rb
step_implementations/specs/job_settings_spec.rb

Adding spec AddNewTemplate.spec

---

Rakefile
lib/context/materials.rb
lib/helpers/spec_helper.rb
lib/pages/admin_pipeline_page.rb
lib/pages/config_xml_page.rb
lib/pages/elastic_agent_profiles_page.rb
lib/pages/general_settings_page.rb
lib/pages/job_details_page.rb
lib/pages/job_settings_page.rb
lib/pages/new_pipeline_dashboard_page.rb
resources/TEST-cruise.testing.JUnit.xml
resources/config/basic-cruise-config.xml
specs/AddNewTemplate.spec
specs/DockerPluginElasticAgentsProfile.spec
specs/JobProperties.spec
step_implementations/go_constants.rb
step_implementations/specs/admin_pipeline_page_spec.rb
step_implementations/specs/elastic_agent_profiles_spec.rb
step_implementations/specs/general_settings_spec.rb
step_implementations/specs/job_details_spec.rb
step_implementations/specs/job_settings_spec.rb

Job properties

---

lib/pages/job_settings_page.rb
lib/pages/pipeline_settings_page.rb
resources/config/basic-cruise-config.xml
specs/FetchArtifactFromAncestorUI.spec
specs/FetchArtifactTask.spec
specs/JobTaskConditions.spec
step_implementations/specs/job_details_spec.rb
step_implementations/specs/job_settings_spec.rb
step_implementations/specs/pipeline_settings_spec.rb

PR for JobTaskConditions,FetchArtifactTask.spec,FetchArtifactFromAncestorUI.spec

Adding spec JobTaskConditions,FetchArtifactTask.spec,FetchArtifactFromAncestorUI.spec

---

specs/SecretConfigAPI.spec
step_implementations/specs/secret_config_api.rb

Added functional test for secret config CRUD API

Functional tests for Secret Config API

---

lib/context/materials.rb
resources/config/secure-cruise-config.xml
specs/CCTrayFeed.spec
specs/PipelineXml.spec
step_implementations/specs/cctray_api_spec.rb
step_implementations/specs/pipeline_api_spec.rb

PR for spec PipelineXML & cctrayfeed

Committing spec PipelineXML & cctrayfeed

---

specs/FanInBehaviourManualAndAutoTriggerForDeepDiamondConfiguration.spec

PR for FanInBehaviourManualAndAutoTriggerForDeepDiamondConfiguration.spec

Committing FanInBehaviourManualAndAutoTriggerForDeepDiamondConfiguration.spec

---

lib/pages/admin_pipeline_page.rb
lib/pages/pipeline_creation_wizard.rb
resources/config/basic-cruise-config.xml
resources/config/secure-cruise-config.xml
specs/ExtractTemplateFromPipeline.spec
specs/PipelineScheduling.spec
step_implementations/specs/admin_pipeline_page_spec.rb

PR for spec ExtractTemplate & PipelineScheduling

Extract template from pipeline

---

step_implementations/initialize.rb

This can be configured as artifact to debug in case of failures

Backup server working directory when run on EFS

---

lib/context/server.rb

Don’t have to run it in regression pipeline, which is mostly for verifying the agent images

Run on all server only in smoke pipeline

---

specs/EditStageAddNewJobFlow.spec

Removed validation of flash messages, validation is done at the actual resource level to see if the save worked

Fix text flakiness

---

Rakefile
lib/helpers/spec_helper.rb
lib/pages/secret_config_spa.rb
specs/SecretConfigSPA.spec
step_implementations/specs/secret_config_spec.rb

Functional test for Secret Config SPA using file-based secret plugin

Spec for Secret Config SPA

---

lib/context/basic_configuration.rb
lib/pages/new_pipeline_dashboard_page.rb
lib/pages/user_summary.rb
step_implementations/go_constants.rb
step_implementations/specs/artifact_store_api_spec.rb
step_implementations/specs/data_sharing_spa_spec.rb
step_implementations/specs/elastic_agent_profiles_CRUD_operations_spec.rb
step_implementations/specs/elastic_profiles_spec.rb
step_implementations/specs/encrypt_api_spec.rb
step_implementations/specs/environments_spark_api.rb
step_implementations/specs/pipeline_api_spec.rb
step_implementations/specs/pipeline_config_api.rb
step_implementations/specs/secret_config_api.rb
step_implementations/specs/templates_api_spec.rb
step_implementations/specs/user_summary_spec.rb
step_implementations/specs/users_roles_api.rb
step_implementations/specs/using_api_spec.rb

Reverts gocd/ruby-functional-tests#486

Revert "Use latest version for all APIs"

---

lib/context/basic_configuration.rb
lib/pages/new_pipeline_dashboard_page.rb
lib/pages/user_summary.rb
step_implementations/go_constants.rb
step_implementations/specs/artifact_store_api_spec.rb
step_implementations/specs/data_sharing_spa_spec.rb
step_implementations/specs/elastic_agent_profiles_CRUD_operations_spec.rb
step_implementations/specs/elastic_profiles_spec.rb
step_implementations/specs/encrypt_api_spec.rb
step_implementations/specs/environments_spark_api.rb
step_implementations/specs/pipeline_api_spec.rb
step_implementations/specs/pipeline_config_api.rb
step_implementations/specs/secret_config_api.rb
step_implementations/specs/templates_api_spec.rb
step_implementations/specs/user_summary_spec.rb
step_implementations/specs/users_roles_api.rb
step_implementations/specs/using_api_spec.rb

Reverts gocd/ruby-functional-tests#487

Revert "Revert "Use latest version for all APIs""

---

lib/helpers/spec_helper.rb
lib/pages/config_repos_page.rb
specs/ConfigReposPipeline.spec
step_implementations/specs/configrepo_spec.rb

Do not merge. Created a basic structure, needs more work to be done.

Added Config repo page validation

---

lib/pages/agents_spa.rb
specs/AgentsUIScreen.spec
specs/ElasticProfiles.spec
step_implementations/specs/agents_spa_spec.rb

Fixing specs related to new Agents SPA.
Can be merged post the new Agents SPA is the default page.

Fixing specs on new agents SPA

---

resources/config/basic-cruise-config.xml
specs/PipelineDependencyChaining.spec

Related to https://github.com/gocd/gocd/issues/7016
I've added the scenario to PipelineDependencyChaining.spec, since it seemed to fit well there. Let me know if any changes are needed.

Add test for pipeline with optional upstream dependency

---

specs/PluginValidations.spec
specs/PluginsTabForm.spec
step_implementations/specs/plugins_spa_spec.rb

- Fixing failure caused by multiple plugin support
- Adding a functional test to check plugins from the bundle are loaded

Plugins bundle support

---

lib/pages/role_config_spa.rb
specs/RolesSPA.spec
step_implementations/specs/role_config_spec.rb

add specs for adding policy during add/edit/clone role config

Specs for configuring policy on roles

---

lib/pages/admin_pipeline_page.rb

Add wait to make sure the object is clickable before doing the action

Another attempt at making sure the pipeline clone happens

---

lib/pages/config_repos_page.rb
resources/config/config-repo-with-policy-secure-cruise-config.xml
resources/config/policy-password.properties
specs/ConfigRepoAPIUserPermissionUsingPolicy.spec
specs/ConfigRepoSPA.spec
step_implementations/specs/config_repo_api.rb
step_implementations/specs/configrepo_spec.rb
step_implementations/specs/configuration_spec.rb

GoCD issues: gocd/gocd#7222, gocd/gocd#7271

Specs for config repo api with policy

---

specs/ConfigRepoAPIUserPermissionUsingPolicy.spec
specs/ConfigRepoSPA.spec

They are not planned for 19.11 releaes

Add tag to config repo policy specs

---

specs/TaskViewerAndEditorValidations.spec

This way timing issues in validating the error message will not occur

Restart the flow of task edit

---

lib/pages/elastic_agent_profiles_page.rb
lib/pages/elastic_profiles_page.rb
specs/ElasticAgentProfilesCRUDOperations.spec
specs/ElasticProfiles.spec
step_implementations/specs/elastic_agent_profiles_CRUD_operations_spec.rb
step_implementations/specs/elastic_agent_profiles_spec.rb
step_implementations/specs/elastic_profiles_spec.rb

Removed scenario for changing cluster id since that is not directly supported on the new page.

Update Cluster and Elastic Profiles specs as per new page

---

resources/config/basic-cruise-config.xml
specs/SecureVariables.spec

To ensure secure environment variable is set to the actual value or not

Add validation

---

lib/helpers/spec_helper.rb
lib/pages/new_pipeline_group_page.rb
specs/NewPipelineGroup.spec
step_implementations/specs/new_pipeline_group_spec.rb

Functional tests for new  pipeline group SPA

---

lib/pages/admin_pipeline_page.rb
specs/EditAnExistingPipelineGroup.spec
step_implementations/specs/admin_pipeline_page_spec.rb

Added specs pertaining to the new flow in GoCD PR https://github.com/gocd/gocd/pull/7239

Updated specs for Pipeline Grp Edit UI

---

step_implementations/initialize.rb

Revert changes done for debugging

Remove empty spec

---

lib/pages/stage_settings_page.rb
specs/EditPipelineWizardPagesAndTabs.spec
step_implementations/specs/stage_settings_spec.rb

- edited a pipeline to add 2nd stage with single job
- ran the pipeline and verified it passes

Added specs for multi-args task

---

resources/config/secure-cruise-config.xml
resources/config/with-config-repo-cruise-config.xml

to include the rules which will allow the tests to pass

Updated the setup cruise-config files

---

lib/pages/compare_pipeline_page.rb
specs/ComparePipelineTimelineView.spec
specs/ComparePipelineWithBisect.spec

The old comparison SPA is being toggled on. Fixing the tests fr the same.

Revert the changes made to test comparison spa

---

lib/pages/package_repository_page.rb
specs/PackageRepositorySPA.spec
step_implementations/specs/package_repository_spec.rb

- Specs for package repo
- Specs for package

Add specs for verifying general flow on package repository spa

---

lib/pages/artifacts_store_page.rb
lib/pages/authorization_config_spa.rb
lib/pages/new_pipeline_group_page.rb
lib/pages/package_repository_page.rb
lib/pages/pluggable_scm_page.rb
lib/pages/secret_config_spa.rb
specs/MaintenanceModeDisableCreation.spec
step_implementations/specs/artifacts_store_spec.rb
step_implementations/specs/authorization_config_spec.rb
step_implementations/specs/new_pipeline_group_spec.rb
step_implementations/specs/package_repository_spec.rb
step_implementations/specs/pluggable_scm_spec.rb
step_implementations/specs/secret_config_spec.rb

when maintenance mode is turned on

Added specs to check that the addition is disabled

---

.gitignore
lib/pages/general_settings_page.rb
lib/pages/job_settings_page.rb
lib/pages/new_environments_page.rb
lib/pages/pipeline_settings_page.rb
lib/pages/publish_artifacts_view.rb
lib/pages/stage_settings_page.rb
resources/config/basic-cruise-config.xml
resources/config/external-artifacts-cruise-config.xml
specs/AdminTaskListing.spec
specs/ArtifactsEdit.spec
specs/ArtifactsEditValidations.spec
specs/AssociatingMultiplePipelinesWithAnEnvironment.spec
specs/EditJob.spec
specs/FanInBehaviorStageFailAndCancel.spec
specs/FetchArtifactFromAncestorUI.spec
specs/FetchArtifactTask.spec
specs/FetchFromExternalArtifacts.spec
specs/HungJobTermination.spec
specs/JobRerunRunMultipleInstance.spec
specs/TaskViewerAndEditor.spec
specs/TaskViewerAndEditorValidations.spec
step_implementations/specs/general_settings_spec.rb
step_implementations/specs/job_settings_spec.rb

DNM: still work in progress
updated specs to use the mithril based page

Updating specs related to job nd job configs 

---

lib/pages/pipeline_settings_page.rb
specs/TfsArtifactUpload.spec
specs/TfsMaterial.spec
specs/TfsMaterialSchedulingAndMaterialModification.spec
step_implementations/specs/pipeline_settings_spec.rb

The specs for TFS still used the element selectors for the old page. Updated them.

Update specs related to TFS for new pipeline config spa

---

lib/pages/preferences_page.rb
resources/config/secure-cruise-config-with-mailhost.xml
specs/PreferencesPage.spec
step_implementations/specs/configuration_spec.rb
step_implementations/specs/preferences_page_spec.rb

Added specs related to notification filter on preferences page

Add specs related to setting notification filters via UI

---

lib/context/agents.rb
lib/context/server.rb
resources/db/db.properties
resources/with-java-agents.sh

- Adding db.properties based on pipeline_counter env var to the server

Update with-java to set up postgres as requireed

---

lib/pages/new_pipeline_dashboard_page.rb
resources/config/secure-cruise-config.xml
specs/DashboardStageOverviewHeader.spec
step_implementations/specs/dashboard_stage_overview_spec.rb

Verify following items:
- renders stage identifier breadcrumb.
- renders triggered by user.
- renders triggered on and total duration.
- stage settings button enabled/disabled state based on user permissions.
- stage rerun button enabled/disabled state based on user permissions.
- stage settings page link.
- stage details page link.
- rerun stage.
- cancel stage.
- renders cancelled by user.
- renders cancelled on.
- renders stage overview for view user.

Specs for Stage Overview Header

---

lib/pages/new_pipeline_dashboard_page.rb
specs/DashboardStageOverview.spec
step_implementations/specs/dashboard_stage_overview_spec.rb

* job is rendered in appropriate state.
* passed/failed/in-progress job count.
* rerun failed/rerun selected btn state.
* rerun failed jobs.
* rerun selected jobs.

Dashboard Stage Overview Spec

---

resources/config/secure-cruise-config.xml
specs/PipelineDashboardManualTriggerWhenPreviousStageIsSuccessful.spec

* When allow only on successful previous stage is set:
* verify the stage manual stage trigger is disabled when previous
stage is failed or cancelled.
* verify the stage manual stage trigger is enabled when previous
stage is passed.

Verify dashboard manual stage trigger enabled state based on previous stage result.

---

lib/helpers/spec_helper.rb
lib/pages/materials_page.rb
resources/config/all-materials-cruise-config.xml
specs/MaterialsSPA.spec
specs/MaterialsSPAWithModifications.spec
step_implementations/specs/configuration_spec.rb
step_implementations/specs/materials_spa_spec.rb

- verified that a user can only view materials for pipelines for which he/she has view permissions
- same goes for usages of a given material
- also verified that the modifications are shown on header and in the modal (in order)

Specs for materials spa

---

Rakefile
lib/pages/package_repository_page.rb
resources/config/package-repo-config.xml
specs/SecretManagementWithPluginAndPackageMaterial.spec

- remove maven poller plugin for packages - use yum instead for secret config usage testing.

Fixing spec failure
